```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!require(matlib)) install.packages("matlib")
if(!require(corpcor)) install.packages("corpcor")
if(!require(MASS)) install.packages("MASS")
if(!require(glmnet)) install.packages("glmnet")
if(!require(dplyr)) install.packages("dplyr")
if(!require(plyr)) install.packages("plyr")
if(!require(ROCR)) install.packages("ROCR")
if(!require(ROCit)) install.packages("ROCit")
library('matlib')
library('corpcor')
library('MASS')
library('glmnet')
library('dplyr')
library('plyr')
library('ROCR')
library('ROCit')
library('ggplot2')
```

```{r set number}
set.seed(10)
#p=sample(x=1:10,size=1)
#p=as.numeric(p)
#n=sample(x=1:15,size=1)
#n=as.numeric(n)
n=50
p=30
#loglambda=seq(-5,500,length.out = 50)
lambda=exp(loglambda)
lambda=seq(0.01,10,length.out = 50)
magnitude = seq(-4, 1, by = 0.05)
lambda = 10 ^ magnitude
??Rev
```

```{r before approaches,echo=FALSE}
#create covariance matrix
creat_num=function() {
  a=sample(x=c(0.5,0),prob=c(0.1,0.9),size=1,replace=T)
  return(a)
}
I=diag(p)
row_fill=1
col_fill=2
matrix_fill=function(){
  repeat{
    if(row_fill==p)
      break
    repeat{
      if(col_fill==p+1)
        break
      I[row_fill,col_fill]=creat_num()
      col_fill=col_fill+1
    }
      row_fill = row_fill + 1
      col_fill = row_fill + 1
    }
  return(I)
}
theta=matrix_fill()
theta[lower.tri(theta)]=t(theta)[lower.tri(theta)]
repeat{
  if(is.positive.definite(theta)==T)
    break
  theta=theta+I
}
theta_cor=cov2cor(theta)
sigma=inv(theta_cor)
#generate random samples
rv=mvrnorm(n=n,mu=rep(0,p),Sigma=sigma)
index=paste("X",1:p,sep="")
colnames(rv)=paste("X",1:p,sep="")
rownames(rv)=c(1:n)
rvdf=data.frame(rv)
sigma2=sigma!=0
```

```{r node-wise lasso 1,echo=FALSE,warning=FALSE}

#I find that we may go wrong direction because ROC curve need different thresholds, which means we need lots of lambda values to ROC curve(one lambda can only generate one point in ROC), So I have changed input in lasso1 function to get different outcomes. 
lasso1=function(i,l){
  #l means lambda
  y=rvdf %>% select(i)
  x = rvdf %>% select(-i)
  x = as.matrix(x)
  y = as.matrix(y)
  #plot(cv.glmnet(x, y, intercept=FALSE))
  #coef = coef(glmnet(x,y,lambda=best_lambda, intercept=FALSE))
  coef = coef(glmnet(x,y,lambda=l, intercept=FALSE))
  coef = as.matrix(coef)
  return(coef)
}

#here we assume that lambda=0.5, I have no idea about the range of lamba we need to choose
result=function(l){
  pred = as.data.frame(t(lasso1(1,l)))
  for (i in seq(2,p)){
    t_coef = as.data.frame(t(lasso1(i,l)))
    t_coef[1,1]=i
    pred = suppressMessages(join(t_coef, pred, type = "full"))
  }
  pred = pred[, -1]
  pred=pred[seq(dim(pred)[1],1),]
  rownames(pred)=paste("Beta(",1:p,",",sep="")
  colnames(pred)=paste(",",1:p,")",sep="") 
  #turn the matrix to T&F to make count convient
  pred = pred!=0
  return(pred)
}
#now to find E_1 and E_2,which are the same as node-wise1 and node-wise2
E_1_finder=function(l){
  E_1=c()
  result=result(l)
  repeat{
    if(row_fill==p)
      break
    repeat{
      if(col_fill==p+1)
        break
      if(result[row_fill,col_fill]== TRUE && result[col_fill,row_fill]==TRUE)
        E_1=c(E_1,paste("(",row_fill,",",col_fill,")",sep=""))
      col_fill=col_fill+1
    }
    row_fill=row_fill+1
    col_fill=row_fill+1
  }
  return(E_1)
}

E_2_finder=function(l){
  E_2=c()
  result=result(l)
  repeat{
    if(row_fill==p)
      break
    repeat{
      if(col_fill==p+1)
        break
      if(result[row_fill,col_fill] == TRUE | result[col_fill,row_fill]==TRUE)
        E_2=c(E_2,paste("(",row_fill,",",col_fill,")",sep=""))
      col_fill=col_fill+1
    }
    row_fill=row_fill+1
    col_fill=row_fill+1
  }
  return(E_2)
}

#I want to creat the confusion matrix,The codes below ignore the value in diagonal

cf_mat_1=function(actu,pred){
  row_fill = 1
  col_fill = 2
  actuT_predT=0
  actuT_predF=0
  actuF_predT=0
  actuF_predF=0
  repeat{
    if(row_fill == p)
      break
    repeat{
      if(col_fill == p+1)
        break
      if(pred[row_fill,col_fill] == actu[row_fill,col_fill]&&pred[col_fill,row_fill] == actu[col_fill,row_fill]){
        if(actu[row_fill,col_fill] == TRUE){
          actuT_predT = actuT_predT + 1}
        else{
          actuF_predF = actuF_predF + 1}}
      else if(pred[row_fill,col_fill] != actu[row_fill,col_fill]&&pred[col_fill,row_fill] != actu[col_fill,row_fill]){
        if(actu[row_fill,col_fill] == TRUE){
          actuT_predF = actuT_predF + 1}
        else{
          actuF_predT = actuF_predT + 1}}
      else if(pred[row_fill,col_fill] == actu[row_fill,col_fill]&&pred[col_fill,row_fill] != actu[col_fill,row_fill]){
        if(actu[row_fill,col_fill] == TRUE){
          actuT_predF = actuT_predF + 1}
        else{
          actuF_predF = actuF_predF + 1}}
      else if(pred[row_fill,col_fill] != actu[row_fill,col_fill]&&pred[col_fill,row_fill] == actu[col_fill,row_fill]){
        if(actu[row_fill,col_fill] == TRUE){
          actuT_predF = actuT_predF + 1}
        else{
          actuF_predF = actuF_predF + 1}}

      col_fill=col_fill+1
    }
    row_fill=row_fill+1
    col_fill=row_fill+1
  }
  cf = matrix(c(actuT_predT,actuT_predF,actuF_predT,actuF_predF),nrow=2,byrow=TRUE)
  colnames(cf)=c("Predict edge exist","Predict edge not exist")
  rownames(cf)=c("Actual edge exist","Actual edge not exist")
  return(cf)
}

#try function below, hope it works
#E_2_finder(l=0.5)
#E_1_finder(l=0.5)
#cf_mat_1(sigma2,result(l=0.141111))
#result(0.141111)
#sigma2
```

```{r,1}
ROC=function(lambda){
  for(l in lambda){
    roc_=cf_mat_1(sigma2,result(l))
    TPR=roc_[1,1]/(roc_[1,1]+roc_[1,2])
    FPR=roc_[2,1]/(roc_[2,1]+roc_[2,2])
    TPR_result = c(TPR_result, TPR)
    FPR_result = c(FPR_result, FPR)
  }
  return(list("TPR_result" = TPR_result, "FPR_result" = FPR_result))
}
result_list = ROC(lambda)
result_df=t(rbind(result_list[["TPR_result"]],result_list[["FPR_result"]]))
result_df=as.data.frame(result_df)
colnames(result_df) = c("TPR","FPR")
View(result_df)
lambda
ggplot(result_df,aes(FPR, TPR))+geom_line()


```
